Models/ErrorViewModel.cs
using System;

namespace KontakTelpon.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Kontak.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace KontakTelpon.Models
{
    public class Kontak
    {
        private static int _counter = 0;

        public Kontak()
        {
            Id = ++_counter;
        }
        public int Id { get; set; }
        public string NamaDepan { get; set; }
        public string NamaBelakang { get; set; }
        public string Email { get; set; }
        public string NoTelp { get; set; }

        [DataType(DataType.Date)]
        public DateTime TanggalLahir { get; set; }
    }
}

Controllers/HomeController.cs
using KontakTelpon.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace KontakTelpon.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/KontakController.cs
using KontakTelpon.Models;
using KontakTelpon.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KontakTelpon.Controllers
{
    public class KontakController : Controller
    {
        private readonly IKontakRepo _repo;

        public KontakController(IKontakRepo repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_repo.GetAllKontak());
        }

        [HttpGet]
        public IActionResult UpSert(int? id)
        {
            if (id != null)
            {
                var kontak = _repo.GetKontakById(id ?? -1);
                if (kontak != null)
                {
                    return View(kontak);
                }
                return NotFound();
            }
            return View();
        }

        [HttpPost]
        public IActionResult Update(Kontak item)
        {
            _repo.UpdateKontak(item);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Create(Kontak item)
        {
            _repo.AddNewKontak(item);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _repo.DeleteKontakById(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("Api/Kontak/Detail")]
        public IActionResult Detail(int id)
        {
            return Json(_repo.GetKontakById(id));
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Kontak/Index.cshtml
@model IEnumerable<Kontak>

@{
    ViewData["Title"] = "List";
}

<h1>List Kontak</h1>

<p>
    <a asp-action="UpSert">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NamaDepan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NamaBelakang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoTelp)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <label>@item.NamaDepan</label>
                </td>
                <td>
                    <label>@item.NamaBelakang</label>
                </td>
                <td>
                    <label>@item.Email</label>
                </td>
                <td>
                    <label>@item.NoTelp</label>
                </td>
                <td>
                    <a asp-action="UpSert" asp-route-id="@item.Id">Edit</a>
                    &nbsp;
                    <a onclick="MakeCall(@item.Id)" data-toggle="modal" data-target="#theModal">Details</a>
                    &nbsp;
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="modal fade text-left" id="theModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="modal-title">Detail Kontak</h4>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <span class="control-label">Nama Depan:&nbsp;</span>
                    <span name="namaDepan" class="control-label"></span>
                </div>
                <div class="form-group">
                    <span class="control-label">Nama Belakang:&nbsp;</span>
                    <label name="namaBelakang" class="control-label"></label>
                </div>
                <div class="form-group">
                    <span class="control-label">Email:&nbsp;</span>
                    <span name="email" class="control-label"></span>
                </div>
                <div class="form-group">
                    <span class="control-label">No Telepon:&nbsp;</span>
                    <span name="noTelepon" class="control-label"></span>
                </div>
                <div class="form-group">
                    <span class="control-label">Tanggal Lahir:&nbsp;</span>
                    <span name="tglLahir" class="control-label"></span>
                </div>
                <button class="btn btn-secondary float-right" data-dismiss="modal">OK</button>
            </div>

        </div>
    </div>
</div>

@section Scripts{
    <script>
        function MakeCall(id) {
            $.ajax({
                url: `/Api/Kontak/Detail?id=${id}`,
                type: `GET`,
                success: (result) => {
                    console.log(result);
                    $("#theModal [name='namaDepan']").text(result.namaDepan);
                    $("#theModal [name='namaBelakang']").text(result.namaBelakang);
                    $("#theModal [name='email']").text(result.email);
                    $("#theModal [name='noTelepon']").text(result.noTelp);
                    $("#theModal [name='tglLahir']").text(result.tanggalLahir);
                    $("#theModal").modal('show');
                }
            });
        }
    </script>
}

Views/Kontak/UpSert.cshtml
@model Kontak

@if (Model != null)
{
    ViewData["Title"] = "Edit";
}
else
{
    ViewData["Title"] = "Create";
}


@if (Model != null)
{
    <h1>Edit</h1>
}
else
{
    <h1>Create</h1>
}

<h4>Kontak</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="@(Model != null ? "Update" : "Create")">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (Model != null)
            {
                <input type="hidden" asp-for="Id" />
            }
            <div class="form-group">
                <label asp-for="NamaDepan" class="control-label"></label>
                <input asp-for="NamaDepan" class="form-control" />
                <span asp-validation-for="NamaDepan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamaBelakang" class="control-label"></label>
                <input asp-for="NamaBelakang" class="form-control" />
                <span asp-validation-for="NamaBelakang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoTelp" class="control-label"></label>
                <input asp-for="NoTelp" class="form-control" />
                <span asp-validation-for="NoTelp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TanggalLahir" class="control-label"></label>
                <input asp-for="TanggalLahir" class="form-control" />
                <span asp-validation-for="TanggalLahir" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KontakTelpon</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KontakTelpon</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kontak" asp-action="Index">Kontak</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - KontakTelpon - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>